title: "Nafees Iqbal"
tagline: "Data Science | Portfolio | Blogs"
url: "https://inafees14.github.io"
author:
  name: "Nafees Iqbal"
  bio: "M.Sc Data Science | Research | Machine Learning"
  email: "your_email@example.com"
